export const REGISTRA_UTENTE_REQUEST = "REGISTRA_UTENTE_REQUEST";
export const REGISTRA_UTENTE_SUCCESS = "REGISTRA_UTENTE_SUCCESS";
export const REGISTRA_UTENTE_FAILURE = "REGISTRA_UTENTE_FAILURE";

export const FETCH_UTENTI_REQUEST = "FETCH_UTENTI_REQUEST";
export const FETCH_UTENTI_SUCCESS = "FETCH_UTENTI_SUCCESS";
export const FETCH_UTENTI_FAILURE = "FETCH_UTENTI_FAILURE";




